name: CI/CD for Expo App (Mobile & Web)

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run tests
        run: yarn test
      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: 🚀 Build app
        run: eas build --platform android --non-interactive --no-wait
      - name: Install Netlify
        run: npm install netlify-cli -g
      - name: Build web
        run: yarn build-web
      - name: Deploy to Netlify
        id: netlify_deploy
        run: |
          netlify deploy \
            --dir ./web-build \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_TOKEN }}
