name: CI/CD for Expo App (Mobile & Web)

on:
  push:
    branches: [ main ]

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run tests
        run: yarn test
      ##todo coverage upload
      - name: Archive build
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: .
  # Deploy eas
  deploy_android:
    runs-on: ubuntu-latest
    # Add a dependency to the build job
    needs: build_test
    # Specify runner + deployment step
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: 🚀 Build app
        run: eas build --profile development --platform android --non-interactive --no-wait
  # Deploy netlify
  deploy_web:
    runs-on: ubuntu-latest
    # Add a dependency to the build job
    needs: build_test
    # Specify runner + deployment step
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
      - name: Install Netlify
        run: npm install netlify-cli -g
      - name: Build web
        run: yarn build-web
      - name: Deploy to Netlify
        id: netlify_deploy
        run: |
          netlify deploy \
            --dir ./dist \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_TOKEN }}
