name: CI/CD for Expo App (Mobile & Web)

on:
  push:
    branches: [ main ]

jobs:
  build_test:
    permissions:                # Job-level permissions configuration starts here
     contents: write
     pages: write
     id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run tests
        run: yarn test
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload the coverage directory from the repository
          path: './coverage/lcov-report'
      ##todo coverage upload
      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: 🚀 Build app
        run: eas build --platform android --non-interactive --no-wait
      - name: Install Netlify
        run: npm install netlify-cli -g
      - name: Build web
        run: yarn build-web
      - name: Deploy to Netlify
        id: netlify_deploy
        run: |
          netlify deploy \
            --dir ./dist \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_TOKEN }}

    # Deploy job
  deploy_coverage:
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    
    # Add a dependency to the build job
    needs: build_test
    # Specify runner + deployment step
    steps:
    #  - name: Set env
    #    run: |
    #      npm i -g semver
    #      echo "GITHUB_VERSION_BUILD=$(echo $(semver 0.1.1 -i prerelease --preid ${{github.run_id}}-${{github.run_number}}-${{github.run_attempt}}))" >> $GITHUB_ENV
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

